/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThesisRouteImport } from './routes/thesis'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as IndexRouteImport } from './routes/index'

const ThesisRoute = ThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/thesis': typeof ThesisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/thesis': typeof ThesisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/practice': typeof PracticeRoute
  '/profile': typeof ProfileRoute
  '/thesis': typeof ThesisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/practice' | '/profile' | '/thesis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/practice' | '/profile' | '/thesis'
  id: '__root__' | '/' | '/practice' | '/profile' | '/thesis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PracticeRoute: typeof PracticeRoute
  ProfileRoute: typeof ProfileRoute
  ThesisRoute: typeof ThesisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thesis': {
      id: '/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof ThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PracticeRoute: PracticeRoute,
  ProfileRoute: ProfileRoute,
  ThesisRoute: ThesisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
